# Load libraries
library(sqldf)
library(DBI)
library(RSQLite)

db <- dbConnect(SQLite(), dbname=myDB)
if ( "SOIL" %in% dbListTables(db))  dbSendQuery(db, "DROP VIEW SOIL")
dbGetQuery(db, "CREATE VIEW SOIL AS
           SELECT SOIL_master.record_id,
           SITESID_master.site,
           SOIL_master.site_id ,
           SOIL_master.table_id,
           SOIL_master.layer_id,
           SOIL_master.date ,
           SOIL_master.horizon ,
           SOIL_master.upperDepth_cm ,
           SOIL_master.lowerDepth_cm ,
           SOIL_master.type_fao ,
           SOIL_master.type_ka5 ,
           SOIL_master.texture ,
           SOIL_master.thickness_cm ,
           SOIL_master.thicknesSigma_cm ,
           SOIL_master.density_gcm3 ,
           SOIL_master.densitySigma_gcm3 ,
           SOIL_master.clay_percent ,
           SOIL_master.claySigma_percent ,
           SOIL_master.silt_percent ,
           SOIL_master.siltSigma_percent ,
           SOIL_master.sand_percent ,
           SOIL_master.sandSigma_percent ,
           SOIL_master.gravel_percent ,
           SOIL_master.ph_h2o ,
           SOIL_master.phSigma_h2o ,
           SOIL_master.phSigma_kcl ,
           SOIL_master.ph_kcl ,
           SOIL_master.ph_cacl2 ,
           SOIL_master.porosity_percent ,
           SOIL_master.fcapv_percent ,
           SOIL_master.wiltpv_percent ,
           SOIL_master.whcp ,
           SOIL_master.whc_mm ,
           SOIL_master.whcSigma_mm ,
           SOIL_master.cec_µeqg ,
           SOIL_master.c_percent ,
           SOIL_master.c_kgm2 ,
           SOIL_master.cSigma_kgm2 ,
           SOIL_master.humus_tCha ,
           SOIL_master.cMax_percent ,
           SOIL_master.cMin_percent ,
           SOIL_master.cOrg_gcm3 ,
           SOIL_master.cOrg_percent ,
           SOIL_master.cOrgSigma_percent ,
           SOIL_master.n_percent ,
           SOIL_master.n_kgm2 ,
           SOIL_master.nMax_percent ,
           SOIL_master.nMin_percent ,
           SOIL_master.nOrg_percent ,
           SOIL_master.nOrgSigma_percent ,
           SOIL_master.cn ,
           SOIL_master.mbC_mgg ,
           SOIL_master.mbCSigma_mgg ,
           SOIL_master.mbN_mgg ,
           SOIL_master.mbNSigma_mgg ,
           SOIL_master.rMin_mgNkgH ,
           SOIL_master.rMinSigma_mgNkgH ,
           SOIL_master.ofhC_percent ,
           SOIL_master.ofh_gDWm2 ,
           SOIL_master.ofhN_percent ,
           SOIL_master.ol_gDWm2 ,
           SOIL_master.bs_percent ,
           SOIL_master.fineRoot_percent ,
           SOIL_master.hydCondSat_cmd1 ,
           SOIL_master.rainGroundWater
           FROM SOIL_master INNER JOIN SITESID_master ON SOIL_master.site_id = SITESID_master.site_id"
)

## Close connnection to db
dbDisconnect(db)


db <- dbConnect(SQLite(), dbname=myDB)
ids <- dbGetQuery(db, "SELECT site_id FROM (SELECT DISTINCT site_id FROM SOIL_master)")

for (i in 1:length(ids[,1])){
  if ( paste("SOIL_", ids[i,], sep="") %in% dbListTables(db))  dbSendQuery(db, paste("DROP VIEW  SOIL_", ids[i,], sep=""))
  
  dbGetQuery(db, paste("CREATE VIEW SOIL_", ids[i,], " AS ",
                       "SELECT SOIL_master.record_id, ",
                       "SITESID_master.site, ",
                       "SOIL_master.site_id , ",
                       "SOIL_master.table_id , ",
                       "SOIL_master.layer_id, ", 
                       "SOIL_master.date , ",
                       "SOIL_master.horizon , ",
                       "SOIL_master.upperDepth_cm , ",
                       "SOIL_master.lowerDepth_cm , ",
                       "SOIL_master.type_fao , ",
                       "SOIL_master.type_ka5 , ",
                       "SOIL_master.texture , ",
                       "SOIL_master.thickness_cm , ",
                       "SOIL_master.thicknesSigma_cm , ",
                       "SOIL_master.density_gcm3 , ",
                       "SOIL_master.densitySigma_gcm3 , ",
                       "SOIL_master.clay_percent , ",
                       "SOIL_master.claySigma_percent , ",
                       "SOIL_master.silt_percent , ",
                       "SOIL_master.siltSigma_percent , ",
                       "SOIL_master.sand_percent , ",
                       "SOIL_master.sandSigma_percent , ",
                       "SOIL_master.gravel_percent , ",
                       "SOIL_master.ph_h2o , ",
                       "SOIL_master.phSigma_h2o , ",
                       "SOIL_master.phSigma_kcl , ",
                       "SOIL_master.ph_kcl , ",
                       "SOIL_master.ph_cacl2 , ",
                       "SOIL_master.porosity_percent , ",
                       "SOIL_master.fcapv_percent , ",
                       "SOIL_master.wiltpv_percent , ",
                       "SOIL_master.whcp , ",
                       "SOIL_master.whc_mm , ",
                       "SOIL_master.whcSigma_mm , ",
                       "SOIL_master.cec_µeqg , ",
                       "SOIL_master.c_percent , ",
                       "SOIL_master.c_kgm2 , ",
                       "SOIL_master.cSigma_kgm2 , ",
                       "SOIL_master.humus_tCha , ",
                       "SOIL_master.cMax_percent , ",
                       "SOIL_master.cMin_percent , ",
                       "SOIL_master.cOrg_gcm3 , ",
                       "SOIL_master.cOrg_percent , ",
                       "SOIL_master.cOrgSigma_percent , ",
                       "SOIL_master.n_percent , ",
                       "SOIL_master.n_kgm2 , ",
                       "SOIL_master.nMax_percent , ",
                       "SOIL_master.nMin_percent , ",
                       "SOIL_master.nOrg_percent , ",
                       "SOIL_master.nOrgSigma_percent , ",
                       "SOIL_master.cn , ",
                       "SOIL_master.mbC_mgg , ",
                       "SOIL_master.mbCSigma_mgg , ",
                       "SOIL_master.mbN_mgg , ",
                       "SOIL_master.mbNSigma_mgg , ",
                       "SOIL_master.rMin_mgNkgH , ",
                       "SOIL_master.rMinSigma_mgNkgH , ",
                       "SOIL_master.ofhC_percent , ",
                       "SOIL_master.ofh_gDWm2 , ",
                       "SOIL_master.ofhN_percent , ",
                       "SOIL_master.ol_gDWm2 , ",
                       "SOIL_master.bs_percent , ",
                       "SOIL_master.fineRoot_percent , ",
                       "SOIL_master.hydCondSat_cmd1 , ",
                       "SOIL_master.rainGroundWater ",
                       "FROM SOIL_master INNER JOIN SITESID_master ON SOIL_master.site_id = SITESID_master.site_id WHERE SOIL_master.site_id = '",
                       ids[i,], "'", sep = "")
  )
}
## Close connnection to db
dbDisconnect(db)




db <- dbConnect(SQLite(), dbname=myDB)
tabs <- dbGetQuery(db, "SELECT DISTINCT table_id FROM SOIL_master")
for (j in 1:length(tabs[,1])){
  ids <- dbGetQuery(db, paste("SELECT site_id FROM (SELECT DISTINCT site_id FROM SOIL_master WHERE table_id = '",
                              tabs[j,],"')", sep =""))
  for (i in 1:length(ids[,1])){
    if ( paste("SOIL_", ids[i,], "_table",tabs[j,], sep="") %in% dbListTables(db))  dbSendQuery(db, paste("DROP VIEW  SOIL_", ids[i,],"_table",tabs[j,], sep=""))
    dbGetQuery(db, paste("CREATE VIEW SOIL_", ids[i,], "_table",tabs[j,], " AS ",
                         "SELECT SOIL_master.record_id, ",
                         "SITESID_master.site, ",
                         "SOIL_master.site_id , ",
                         "SOIL_master.table_id , ",
                         "SOIL_master.layer_id, ", 
                         "SOIL_master.date , ",
                         "SOIL_master.horizon , ",
                         "SOIL_master.upperDepth_cm , ",
                         "SOIL_master.lowerDepth_cm , ",
                         "SOIL_master.type_fao , ",
                         "SOIL_master.type_ka5 , ",
                         "SOIL_master.texture , ",
                         "SOIL_master.thickness_cm , ",
                         "SOIL_master.thicknesSigma_cm , ",
                         "SOIL_master.density_gcm3 , ",
                         "SOIL_master.densitySigma_gcm3 , ",
                         "SOIL_master.clay_percent , ",
                         "SOIL_master.claySigma_percent , ",
                         "SOIL_master.silt_percent , ",
                         "SOIL_master.siltSigma_percent , ",
                         "SOIL_master.sand_percent , ",
                         "SOIL_master.sandSigma_percent , ",
                         "SOIL_master.gravel_percent , ",
                         "SOIL_master.ph_h2o , ",
                         "SOIL_master.phSigma_h2o , ",
                         "SOIL_master.phSigma_kcl , ",
                         "SOIL_master.ph_kcl , ",
                         "SOIL_master.ph_cacl2 , ",
                         "SOIL_master.porosity_percent , ",
                         "SOIL_master.fcapv_percent , ",
                         "SOIL_master.wiltpv_percent , ",
                         "SOIL_master.whcp , ",
                         "SOIL_master.whc_mm , ",
                         "SOIL_master.whcSigma_mm , ",
                         "SOIL_master.cec_µeqg , ",
                         "SOIL_master.c_percent , ",
                         "SOIL_master.c_kgm2 , ",
                         "SOIL_master.cSigma_kgm2 , ",
                         "SOIL_master.humus_tCha , ",
                         "SOIL_master.cMax_percent , ",
                         "SOIL_master.cMin_percent , ",
                         "SOIL_master.cOrg_gcm3 , ",
                         "SOIL_master.cOrg_percent , ",
                         "SOIL_master.cOrgSigma_percent , ",
                         "SOIL_master.n_percent , ",
                         "SOIL_master.n_kgm2 , ",
                         "SOIL_master.nMax_percent , ",
                         "SOIL_master.nMin_percent , ",
                         "SOIL_master.nOrg_percent , ",
                         "SOIL_master.nOrgSigma_percent , ",
                         "SOIL_master.cn , ",
                         "SOIL_master.mbC_mgg , ",
                         "SOIL_master.mbCSigma_mgg , ",
                         "SOIL_master.mbN_mgg , ",
                         "SOIL_master.mbNSigma_mgg , ",
                         "SOIL_master.rMin_mgNkgH , ",
                         "SOIL_master.rMinSigma_mgNkgH , ",
                         "SOIL_master.ofhC_percent , ",
                         "SOIL_master.ofh_gDWm2 , ",
                         "SOIL_master.ofhN_percent , ",
                         "SOIL_master.ol_gDWm2 , ",
                         "SOIL_master.bs_percent , ",
                         "SOIL_master.fineRoot_percent , ",
                         "SOIL_master.hydCondSat_cmd1 , ",
                         "SOIL_master.rainGroundWater ",
                         "FROM SOIL_master INNER JOIN SITESID_master ON SOIL_master.site_id = SITESID_master.site_id WHERE SOIL_master.site_id = '",
                         ids[i,], "' AND table_id = '", tabs[j,] , "'", sep = "")
    )
  }
  
}

## Close connnection to db
dbDisconnect(db)
